// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getfeedidbyurl.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedIDByUrl = `-- name: GetFeedIDByUrl :one
SELECT id FROM feeds
WHERE url = $1
`

func (q *Queries) GetFeedIDByUrl(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getFeedIDByUrl, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
