// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getfeedfromfeedid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedFromFeedID = `-- name: GetFeedFromFeedID :one
SELECT id, created_at, updated_at, name, url, user_id FROM feeds
    WHERE feeds.id = $1
`

func (q *Queries) GetFeedFromFeedID(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedFromFeedID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
