// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: postsbyfeedid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const postsByFeedID = `-- name: PostsByFeedID :many
SELECT id, created_at, updated_at, title, url, description, published_at, feed_id FROM posts
WHERE feed_id = $1
ORDER BY published_at ASC
LIMIT $2
`

type PostsByFeedIDParams struct {
	FeedID uuid.UUID
	Limit  int
}

func (q *Queries) PostsByFeedID(ctx context.Context, arg PostsByFeedIDParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, postsByFeedID, arg.FeedID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
