// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: userfromid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserFromID = `-- name: GetUserFromID :one
SELECT id, created_at, updated_at, name FROM users
    WHERE users.id = $1
`

func (q *Queries) GetUserFromID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
